FROM golang:alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/server ./cmd/server/main.go

FROM alpine:latest

WORKDIR /app
RUN apk add --no-cache ca-certificates tzdata

COPY --from=builder /app/server .
# Create a user to run as non-root
RUN adduser -D appuser
USER appuser

EXPOSE 9380
CMD ["./server", "-c", "conf/service_conf.yaml"]
