apiVersion: v1
kind: Service
metadata:
  name: {{ include "ragflow.fullname" . }}-web
  labels:
    app: ragflow-web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ragflow-web
